language: node_js
node_js:
  - "stable"
  - "unstable"
  - "iojs"
before_script:
  - npm i jscoverage coveralls grunt-cli nodeunit
script: "./node_modules/.bin/grunt test"
after_script:
  - ./node_modules/.bin/jscoverage lib
  - EXPRESVERIFIER_COV=1 ./node_modules/.bin/nodeunit --reporter=lcov tests/ | ./node_modules/.bin/coveralls
notifications:
  email:
    on_success: never
    on_failure: always
